/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasikonversisuhu;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Win 10
 */
public class JframeAplikasiKonversiSuhu extends javax.swing.JFrame {

    /**
     * Creates new form JframeAplikasiKonversiSuhu
     */
    public JframeAplikasiKonversiSuhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtResult = new javax.swing.JTextField();
        cbKonversi = new javax.swing.JComboBox<>();
        btnKonversi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbToCelcius = new javax.swing.JRadioButton();
        rbToReamur = new javax.swing.JRadioButton();
        rbToKelvin = new javax.swing.JRadioButton();
        suhu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rbToFahrenheit = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtResult.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtResultKeyTyped(evt);
            }
        });

        cbKonversi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Reamur", "Kelvin" }));
        cbKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKonversiActionPerformed(evt);
            }
        });

        btnKonversi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnKonversi.setText("KONVERSI");
        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("SUHU");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("KONVERSI  KE");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("SATUAN");

        rbToCelcius.setText("Celcius");

        rbToReamur.setText("Reamur");
        rbToReamur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbToReamurActionPerformed(evt);
            }
        });

        rbToKelvin.setText("Kelvin");
        rbToKelvin.setActionCommand("Kelvin");
        rbToKelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbToKelvinActionPerformed(evt);
            }
        });

        suhu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                suhuKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("HASIL");

        rbToFahrenheit.setText("Fahrenheit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(btnKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbKonversi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbToCelcius)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(rbToFahrenheit)
                                .addGap(18, 18, 18)
                                .addComponent(rbToReamur)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbToKelvin))
                            .addComponent(suhu))
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(suhu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbToCelcius)
                    .addComponent(rbToReamur)
                    .addComponent(rbToKelvin)
                    .addComponent(rbToFahrenheit))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("APLIKASI KONVERSI SUHU");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
         
                konversiSuhu();
          
    }//GEN-LAST:event_btnKonversiActionPerformed

    private void rbToReamurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbToReamurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbToReamurActionPerformed

    private void rbToKelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbToKelvinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbToKelvinActionPerformed

    private void cbKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKonversiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKonversiActionPerformed

    private void suhuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_suhuKeyTyped
        char c = evt.getKeyChar();
            if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
                evt.consume(); // Mencegah karakter yang bukan angka
                JOptionPane.showMessageDialog(null,
                         "Masukkan angka yang valid!",
                        "Error",
                         JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_suhuKeyTyped

    private void txtResultKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResultKeyTyped
        
        txtResult.setText(" ");
    }//GEN-LAST:event_txtResultKeyTyped

      
     private void konversiSuhu() {
        try {
            double suhu1 = Double.parseDouble(suhu.getText());
            String hasil = "";
            
            if (rbToCelcius.isSelected()) {
                hasil = "Celcius: " + toCelcius(suhu1);
            } else if (rbToFahrenheit.isSelected()) {
                hasil = "Fahrenheit: " + toFahrenheit(suhu1);
            } 
            else if (rbToReamur.isSelected()) {
                hasil = "Reamur: " + toReamur(suhu1);
            } else if (rbToKelvin.isSelected()) {
                hasil = "Kelvin: " + toKelvin(suhu1);
            }
            
            txtResult.setText(hasil);
        } catch (NumberFormatException ex) {
            txtResult.setText("Input tidak valid!");
        }
    }
     
      private double toCelcius(double suhu1) {
        switch (cbKonversi.getSelectedIndex()) {
            case 1: return (suhu1 - 32) * 5 / 9; // Fahrenheit to Celcius
            case 2: return suhu1 * 5 / 4; // Reamur to Celcius
            case 3: return suhu1 - 273.15; // Kelvin to Celcius
            default: return suhu1; // Celcius ke Celcius
        }
    }
    
    // Konversi dari Celcius ke Fahrenheit
    private double toFahrenheit(double suhu1) {
        switch (cbKonversi.getSelectedIndex()) {
            case 0: return suhu1 * 9 / 5 + 32; // Celcius to Fahrenheit
            case 2: return (suhu1 * 9 / 5) + 32; // Reamur to Fahrenheit
            case 3: return (suhu1 - 273.15) * 9 / 5 + 32; // Kelvin to Fahrenheit
            default: return suhu1; // Fahrenheit to Fahrenheit
        }
    }
 
    
    // Konversi dari Celcius ke Reamur
    private double toReamur(double suhu1) {
        switch (cbKonversi.getSelectedIndex()) {
            case 0: return suhu1 * 4 / 5; // Celcius to Reamur
            case 1: return (suhu1 - 32) * 4 / 9; // Fahrenheit to Reamur
            case 3: return (suhu1 - 273.15) * 4 / 5; // Kelvin to Reamur
            default: return suhu1; // Reamur to Reamur
        }
    }
    
        private double toKelvin(double suhu1) {
        switch (cbKonversi.getSelectedIndex()) {
            case 0: return suhu1 + 273.15; // Celcius to Kelvin
            case 1: return (suhu1 - 32) * 5 / 9 + 273.15; // Fahrenheit to Kelvin
            case 2: return (suhu1 * 5 / 4) + 273.15; // Reamur to Kelvin
            default: return suhu1; // Kelvin to Kelvin
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeAplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeAplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeAplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeAplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeAplikasiKonversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKonversi;
    private javax.swing.JComboBox<String> cbKonversi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbToCelcius;
    private javax.swing.JRadioButton rbToFahrenheit;
    private javax.swing.JRadioButton rbToKelvin;
    private javax.swing.JRadioButton rbToReamur;
    private javax.swing.JTextField suhu;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables

   
}
